using Dapper; using LotteryLab.Api.Data; using LotteryLab.Api.Models; using LotteryLab.Api.Services; using Microsoft.AspNetCore.Mvc;
namespace LotteryLab.Api.Controllers;
[ApiController][Route("api")]
public sealed class ApiController(Db db,PdfImportService pdf,AnalysisService analysis,AiService ai):ControllerBase {
 [HttpPost("imports/preview")][RequestSizeLimit(20_000_000)] public IActionResult Preview(IFormFile file){using var s=file.OpenReadStream(); return Ok(pdf.Parse(s,file.FileName));}
 [HttpPost("imports/commit")] public async Task<IActionResult> Commit(ImportPreview x){if(x.Date is null||x.Time is null)return BadRequest("Data/horário ausentes"); using var c=db.Open(); using var tx=c.BeginTransaction(); var id=await c.ExecuteScalarAsync<long>(@"insert into extractions(bank,extraction_date,extraction_time,source_file) values(@Bank,@Date,@Time::time,@FileName) on conflict(bank,extraction_date,extraction_time) do update set source_file=excluded.source_file returning id",new{x.Bank,x.Date,x.Time,x.FileName},tx); await c.ExecuteAsync("delete from results where extraction_id=@id",new{id},tx); foreach(var r in x.Results) await c.ExecuteAsync(@"insert into results(extraction_id,position,number,centena,dezena,group_no,animal) values(@id,@Position,@Number,@Centena,@Dezena,@Group,@Animal)",new{id,r.Position,r.Number,r.Centena,r.Dezena,Group=r.Group,r.Animal},tx); tx.Commit(); return Ok(new{id,count=x.Results.Count});}
 [HttpGet("history")] public async Task<IActionResult> History(string bank="LT NACIONAL",int take=100){using var c=db.Open(); return Ok(await c.QueryAsync(@"select e.id,e.bank,e.extraction_date,e.extraction_time,count(r.id) results from extractions e left join results r on r.extraction_id=e.id where e.bank=@bank group by e.id order by e.extraction_date desc,e.extraction_time desc limit @take",new{bank,take}));}
 [HttpGet("forecast")] public async Task<IActionResult> Forecast(string bank="LT NACIONAL",string time="21:00",int windowDays=15,int top=8)=>Ok(await analysis.Forecast(bank,time,windowDays,top));
 [HttpGet("backtest")] public async Task<IActionResult> Backtest(string bank="LT NACIONAL",string time="21:00",int windowDays=15,int top=8)=>Ok(await analysis.Backtest(bank,time,windowDays,top));
 [HttpPost("ai/analyze")] public async Task<IActionResult> Ai(AiRequest req){var f=await analysis.Forecast(req.Bank,req.Time,req.WindowDays,8);var b=await analysis.Backtest(req.Bank,req.Time,req.WindowDays,8);return Ok(new{answer=await ai.Ask(new{forecast=f,backtest=b},req.Question)});}
}
